services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      - N8N_HOST={N8N_HOST}
      - N8N_PORT={N8N_PORT}
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - N8N_SKIP_AUTH_ON_OAUTH_CALLBACK=true
    ports:
      - "{N8N_PORT}:{N8N_PORT}"
    volumes:
      - ./n8n_data:/home/node/.n8n
